name=Ino Interpreter
version=0.0.0
author=YH Choi <yhei.choi@gmail.com>
maintainer=YH Choi <yhei.choi@gmail.com>
sentence=Arduino Interpreter.
paragraph=Interprets Arduino standard API calls.
category=Uncategorized
url=https://github.com/YH-Choi-001/ino-interpreter
architectures=*
includes=InoInterpreter.h
